[book]
authors = ["dj1vs"]
language = "ru"
multilingual = false
src = "src"
title = "Курс по C++"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "rust"